--Greenplum

BEGIN WORK;
create table funds_load_batchs
  (
    ser_no SERIAL,
	funds_batch_no INTEGER,
    user_id CHARACTER VARYING(80),
    employer_id CHARACTER VARYING(15),
    funds_batch_date DATE,
    funds_batch_time TIMESTAMP(6) WITHOUT TIME ZONE,
    funds_batch_file CHARACTER VARYING(120),
    remarks CHARACTER VARYING(255),
    funds_err_file CHARACTER VARYING(255),
    nbad_trans INTEGER,
    tot_amount DECIMAL(12,2),
    ntrans INTEGER,
    batch_status CHAR(1),
    ncur_bad_trans INTEGER,
    description CHARACTER VARYING(60),
    card_no CHARACTER VARYING(19),
    account_no CHARACTER VARYING(29),
    account_title CHARACTER VARYING(60),
    account_type CHAR(2),
    routing_no CHARACTER VARYING(9),
    ntrans_done INTEGER,
    ntrans_failed INTEGER,
    amount_done DECIMAL(12,2),
    fund_batch_types CHAR(1),
    prefund_auth_flag CHAR(1),
    is_fee_prefund CHAR(1),
    trace_audit_no INTEGER,
    authorized_on DATE,
    authorized_at TIMESTAMP(6) WITHOUT TIME ZONE,
    auth1_user_id CHARACTER VARYING(20),
    auth2_user_id CHARACTER VARYING(20),
    fee_on_load_amount DECIMAL(12,2),
    total_fees_per_record DECIMAL(12,2),
    fee_amount DECIMAL(12,2),
    tot_load_amount DECIMAL(12,2),
    fileformat CHAR(1),
    credit_amount DECIMAL(12),
    debit_amount DECIMAL(12),
    is_forced_post CHAR(1),
    is_neg_bal_allowed CHAR(1),
    funds_file_id INTEGER,
	time_spent TIMESTAMP(6) WITHOUT TIME ZONE,
    service_id CHARACTER VARYING(20),
    is_fee_trans CHAR(1),
    batch_start_at TIMESTAMP(6) WITHOUT TIME ZONE,
    batch_end_at TIMESTAMP(6) WITHOUT TIME ZONE,
    last_processed_sr_no INTEGER,
    cust_fees_per_record DECIMAL(12,2),
    fund_payment_channel_id smallint,
    decline_reason CHARACTER VARYING(255),
    decline_on TIMESTAMP(6) WITHOUT TIME ZONE,
    decline_user_id CHARACTER VARYING(80),
    auth1_at TIMESTAMP(6) WITHOUT TIME ZONE,
    apply_batch_fee CHAR(1),
    batch_fee_applied CHAR(1),
    no_of_attempts smallint,
    last_attempt_at TIMESTAMP(6) WITHOUT TIME ZONE,
    last_processed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    copy_bat_desc2recs CHAR(1),
    batch_curr_code CHARACTER VARYING(3),
    cust_fee_curr_code CHARACTER VARYING(3),
    tot_fee_ch_card DECIMAL(12,2),
    amount_loaded DECIMAL(12,2),
    tot_amt_processed DECIMAL(12,2),
    ext_ref_no INTEGER,
    signature_file_id INTEGER,
    bank_name CHARACTER VARYING(60),
    branch_name CHARACTER VARYING(60),
    app_id INTEGER,
    is_admin_batch CHAR(1),
    funds_expiry_date DATE,
    login_ip CHARACTER VARYING(15),
    login_date DATE,
    
    device_id CHARACTER VARYING(64),
    client_device_data CHARACTER VARYING(250),
	instance_id CHARACTER VARYING(4),
	rec_sync_created_at TIMESTAMP WITHOUT TIME ZONE,
	rec_last_sync_updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
	t SMALLINT
  );
WITH (appendonly=true, orientation=column, compresstype=zlib, compresslevel=6, blocksize=524288)
DISTRIBUTED BY (ser_no);
GRANT SELECT, INSERT, UPDATE, DELETE on funds_load_batchs to app_role;
GRANT usage, SELECT, UPDATE ON funds_load_batchs_ser_no_seq TO app_role;

COMMIT WORK;

